### ISSUE TITLE
npm package does not contain source maps, but contains v6.x files (?)

### ISSUE THREAD

**Issue by paolostyle** [tannerlinsley/react-table#1416]
Pretty much in the title. I created a table a while ago using alpha.6 and now I wanted to update it to the latest alpha. Obviously something is not working, but it's a a bit rough to figure out what's wrong when an error looks like this...
![image](https://user-images.githubusercontent.com/8234991/62070157-3c3d2c00-b23a-11e9-93c6-f4239b2ae3ed.png)

I checked the folder structure of node_modules/react-table and there are no source maps, but... it seems like there are actually both v6 and v7?

![image](https://user-images.githubusercontent.com/8234991/62070426-bf5e8200-b23a-11e9-8fa2-78e217c94875.png)

Obviously those v6 files are not in my bundle or anything, but it just doesn't make sense in my opinion to include both (or even src, for that matter).

I forked the repo to check if it needs fixing or something, but it seems like source maps and ES modules build (dist/index.es.js) are actually produced by Rollup, they're just not published properly. Can you please fix that? This is all on react-table@7.0.0-alpha.12.

**Comment by tannerlinsley** [comment]
Good find. Yes, the next alpha will have all of those artifacts removed. Thanks!

**Comment by tannerlinsley** [comment]
Should be fixed now

**Comment by paolostyle** [comment]
Unfortunately it seems like it's still not resolved completely. 
![image](https://user-images.githubusercontent.com/8234991/62160709-e5f0eb80-b314-11e9-887a-72186706e4f2.png)
react-table.js and react-table.css are not needed anymore, but more importantly there's still no index.es.js and source maps. I believe you need to update `files` field in the package.json. The screen is from alpha.14.

**Comment by tannerlinsley** [comment]
Can you confirm any difference with alpha.15?

**Comment by paolostyle** [comment]
Yes, now it looks fine! Thanks for a super quick resolution.
