### ISSUE TITLE
useSort problems

### ISSUE THREAD

**Issue by toastyboost** [tannerlinsley/react-table#1430]
Thanks for developing react table v7!

Well, i noticed that client sorting works not well! You can see it at default example
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/sorting-client-side

https://gyazo.com/10fa8c78e1d9a363980fc22aca4df690
At some moment its freezing, and after 4-6 sortings it make ~12k renders, just watch at console.

On my production website - page just crash while i trying to sort!

Thank you for help!

**Comment by tannerlinsley** [comment]
Where is your console.log? Can you please link to the code sandbox you used in your video?

**Comment by gargroh** [comment]
To provide more information 
- If `developer tool` is open then it is freezing else it is working fine.
- Independent of `debug` flag

**Comment by toastyboost** [comment]
Well, click here https://codesandbox.io/s/tannerlinsleyreact-table-sorting-client-side-hj4sg
Then click multiple time to First Name / Last Name header group like on this GIF
https://gyazo.com/10fa8c78e1d9a363980fc22aca4df690

then look at console 
https://gyazo.com/b6206311eedb6e537f8746762390b3d6

2-3 sorting make 4000 debug strings
when i tried it my browser - its crashing

**Comment by tannerlinsley** [comment]
Indeed. Looks like a regression. Will get to work on this.

**Comment by tannerlinsley** [comment]
Fixed in latest release (>7.0.0-alpha.19)

**Comment by toastyboost** [comment]
Whoa! Big thanks!

**Comment by pkhodaveissi** [comment]
I've been using version alpha.19 but this error still exist, I have switched to alpha.21 yet still I see this happens in development it goes to a loop and in production react crashes to error `Error: Minified React error #185;

**Comment by pkhodaveissi** [comment]
I must add this behavior only surfaces when useSort is used along usePagination

**Comment by pkhodaveissi** [comment]
something else I should mention is that another condition for this to appear is that defaultColumn object is not present to useTable config like so:

```
const defaultColumn = {
sort: "alphanumeric"
};
```
