### ISSUE TITLE
disablePageResetOnDataChange not working properly

### ISSUE THREAD

**Issue by dalvallana** [tannerlinsley/react-table#1506]
**Describe the bug**
Using v7. Having `disablePageResetOnDataChange` off by default and then set it to on works properly, but then setting it to off again doesn't have any effect. It seems that setting `disablePageResetOnDataChange` to `true` makes it impossible to change it back to `false`.

**To Reproduce**
I modified the **editable cells** example to add sorting capability >> https://codesandbox.io/s/tannerlinsleyreact-table-editable-data-xwl8m.
1. Go to page 2.
2. Edit one of the cells. Unfocus the cell so the data change is triggered. The page is not reset (which is the expected behaviour).
3. Click on ny header in order to sort by that column. Observe that the page number keeps being 2, even though `disablePageResetOnDataChange` was turned off after data change.

**Expected behavior**
After changing data and turning `disablePageResetOnDataChange` back off, the pageIndex should be reset to zero when sorting by any column.

**Codesandbox!**
https://codesandbox.io/s/tannerlinsleyreact-table-editable-data-xwl8m

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser Chrome and Safari, latest versions.

**Comment by tannerlinsley** [comment]
This is fixed in the latest alpha release

**Comment by tannerlinsley** [comment]
Be sure to check out the changes to the example: https://github.com/tannerlinsley/react-table/commit/0aa55dac08a8a4381548a7d5366b247c440a5d4c

**Comment by dalvallana** [comment]
Hi @tannerlinsley! Thanks for the update. I still see this happening in the example, though. I am using alpha 35 release.

**Comment by tannerlinsley** [comment]
You have to update your example to use state, as shown in the diff. Here is my updated fork: https://codesandbox.io/s/tannerlinsleyreact-table-editable-data-gvmnd

**Comment by dalvallana** [comment]
Oh! sorry, I didn't get that part. Thanks a lot!
