### ISSUE TITLE
Unable to deselect row

### ISSUE THREAD

**Issue by SumeetGohil** [tannerlinsley/react-table#1797]
**Unable to deselect row when applied with Filter Column**

**Steps to Reproduce:**

1. Filter by any column (Works as Expected)
2. Select particular row by ticking checkbox. (Works as Expected)
3. Deselect same row (Doesn't Works as Expected)

![bug](https://user-images.githubusercontent.com/1188769/71237157-c770a880-2326-11ea-923a-7ca1dd7048c0.gif)

**Laptop Info**

- MacBook Pro (Retina, 13-inch, Early 2015) (Mojave- 10.14.4)
- Browser: Chrome Version 79.0.3945.79 (Official Build) (64-bit)

**Comment by tannerlinsley** [comment]
Looking in to this asap

**Comment by tannerlinsley** [comment]
This will be fixed in the next release.

**Comment by fionawhim** [comment]
Hey, I just ran across this myself. Was wondering if a fix was ready on master awaiting a release, or if you still needed someone to fix it.

**Comment by Satwinder236** [comment]
In node-modules/react-table/dist/index.js, on line number 2869
replace this line 
var isSelected = row.isSelected;
with
var isSelected = state.selectedRowIds[row.id];
Refer the attached image
<img width="776" alt="row-deselect-fix" src="https://user-images.githubusercontent.com/58903046/73739713-c677c700-476c-11ea-88d2-8a61d4748465.png">

**Comment by fionawhim** [comment]
I ended up adding a plugin with a `useInstance` lifecycle that goes between `useFilters` and `useRowSelect`. The root cause of this seems to be `useFilters` generating `rows` and `flatRows` arrays that have different objects in them. My plugin just re-generates `flatRows` from `rows` before things get passed to `useRowSelect`.

**Comment by SourceCipher** [comment]
When is the fix planned to be released? I can still replicate [here ](https://codesandbox.io/s/infallible-star-lrzgb) with the latest version.

**Comment by ifen** [comment]
Any solution please? As this is really holding us back from using this library and we absolutely can't wait to use it because it's amazing @tannerlinsley Thank you so much.

**Comment by fionawhim** [comment]
@ifen Try this: https://gist.github.com/fionawhim/c49fa6cb2257af0a03fb7e09ea1e7583

And use it like this:

```
  return useTable(
    {
      columns,
      data: groupedFeatures,
      …
    },
    useFilters,
    useFiltersPatch,
    useRowSelect
  );
```

**Comment by tannerlinsley** [comment]
This is fixed in master and slated for release. Thanks for your help everyone!

**Comment by fionawhim** [comment]
@tannerlinsley I just cloned/built the repo and used `yarn link` to try out the master branch in my app. I’m still seeing this bug occur: if a filter is active on the table, deselection doesn’t work.

I looked over the code in the repo and I hypothesize that `rows` and `flatRows` containing different object instances when there’s a filter is causing the problem.

**Comment by tannerlinsley** [comment]
Good to know. I’ll dig deeper.
