### ISSUE TITLE
Compatibility of useAbsoluteLayout and useResizeColumns

### ISSUE THREAD

**Issue by gargroh** [tannerlinsley/react-table#1827]
When using both `useAbsoluteLayout` and `useResizeColumns` together then header cells are taking `position: relative` die to which layout is breaking, can be reproduced at following link :- 

https://codesandbox.io/s/elated-sound-nbyov

**Comment by tannerlinsley** [comment]
This will be fixed in the next release.

**Comment by tannerlinsley** [comment]
This is fixed in master and slated for release. Thanks for your help everyone!

**Comment by wwsskkaa** [comment]
is there a working example of useAbsoluteLayout and useResizeColumns together? I still can't get this two to work together
