### ISSUE TITLE
TypeError Cannot read property 'push' of undefined in Kitchen Sink Example

### ISSUE THREAD

**Issue by seanraad123** [tannerlinsley/react-table#1909]
**Describe the bug**
Error appears right when you go to the kitchen sink example

**To Reproduce**

1. Go to [https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/kitchen-sink](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/kitchen-sink)
2. See error

![Screen Shot 2020-02-14 at 4 49 16 PM](https://user-images.githubusercontent.com/28455325/74570137-02b7de00-4f4a-11ea-9a08-ebf3491b6e3a.png)

**Comment by pmorgan3** [comment]
The visibleColumns property doesn't exist yet. It will when @tannerlinsley releases it.

**Comment by tannerlinsley** [comment]
Coming asap. Hang tight :)

**Comment by phoang63** [comment]
Hello:

I get error when running tannerlinsley-react-table-row-selection

It works on code-pen but failed when I download and run "yarn install/yarn start",

Thank You

TypeError: Cannot read property 'push' of undefined

(anonymous function)
C:/Udemy3/react-npm/tannerlinsley-react-table-row-selection/src/App.js:70
  67 | },
  68 | useRowSelect,
  69 | hooks => {
> 70 |   hooks.visibleColumns.push(columns => [
     | ^  71 |     // Let's make a column for selection
  72 |     {
  73 |       id: 'selection',

**Comment by farishan** [comment]
It's July 2020.

Any update about visibleColumns?

**Comment by tannerlinsley** [comment]
Should be working. Do you have a codesandbox example I can look at ?

**Comment by dariatsenter** [comment]
I can confirm this was fixed for me when I upgraded from 7.0.0 to 7.5.0 :raised_hands:

**Comment by myerzman** [comment]
Still not working for me, did a brand new install of material-UI-kitchen-sink. code pen works though ...
![Screen Shot 2021-01-13 at 11 55 33 AM](https://user-images.githubusercontent.com/707061/104443525-d6ac3f00-5596-11eb-9f21-17e802391188.png)

**Comment by nedislavd** [comment]
> Still not working for me, did a brand new install of material-UI-kitchen-sink. code pen works though ...
> ![Screen Shot 2021-01-13 at 11 55 33 AM](https://user-images.githubusercontent.com/707061/104443525-d6ac3f00-5596-11eb-9f21-17e802391188.png)

Seems like the example's "latest" version of react-table points at version "7.0.0-rc.15". 
Changing it manually to 7.6.3 fixes the issue 
![image](https://user-images.githubusercontent.com/7418108/108365537-01c22800-7200-11eb-802b-ae662025127a.png)
