### ISSUE TITLE
nextPage and goToPage don't work well

### ISSUE THREAD

**Issue by ikkiphoenix** [tannerlinsley/react-table#2321]
Hello, 

i have done npm update and when i done it, i got the new version of react-table. but in doing so, nextPage and goToPage in manualPagination don't work anymore so i come back to v7 and it work well.

I try with 7.0.4 and it works too.

Thanks

**Comment by BjoernRave** [comment]
yes,I have the same problem. `goToPage` breaks when upgrading to `7.1.0`, but works well on `7.0.4`

**Comment by alecananian** [comment]
It looks like the `goToPage` function used to work when used in conjunction with `manualPagination` mode without a `pageCount` specified, but that appears to be removed in v7.1.0.  The `pageCount` property is now required, as explained in the docs: [Table Options > pageCount](https://github.com/tannerlinsley/react-table/blob/master/docs/api/usePagination.md#table-options).

The [pagination-controlled](https://github.com/tannerlinsley/react-table/blob/88a0d86d60022731e6914551a1709d733fc40724/examples/pagination-controlled/src/App.js#L43) example app provides some sample code you can reference.

**Comment by jnhooper** [comment]
I came across this trying to figure out why `nextPage` would only fire every other time i tried to fire it. turns out that `pageCount` should _only_ be defined if you are doing manualPagination. at least that fixed my issue client side pagination being a little wonky

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version with a few commits going towards pagination fixes.

**Comment by sep2** [comment]
This problem still exists in 7.7.0, the `gotoPage` does not fire when `manualPagination` is false, but it will fire when `manualPagination` is true.

```
useTable(
        {
            columns,
            data,
            initialState,
            manualSortBy: true,
            disableMultiSort: true,
            pageCount: -1,
            manualPagination: false,
            autoResetPage: false,
        },
        useSortBy,
        usePagination
    )
```

**Comment by artemis-prime** [comment]
Please re-open @tannerlinsley

**Comment by supalogix** [comment]
I am also experiencing this problem. Is this issue resolved?

**Comment by supalogix** [comment]
I have the same problem as @sep2 and are using 7.7.0:  the gotoPage does not fire when manualPagination is false, but it will fire when manualPagination is true.

This is how we currently populate our table.

```
  const {
    getTableProps,
    headers,
    page,
    prepareRow,
    gotoPage,
    nextPage,
    previousPage,
    setPageSize,
    rows,
    pageCount,
    state: { pageIndex, pageSize }
  } = useTable(
    {
      columns,
      data,
//      manualPagination: true,
      disableSortRemove:true,
      initialState: {
        pageIndex: 0,
        pageSize: 10,
        sortBy: [
          {
            id: columns.at(0)?.accessor,
            desc: false
          }
        ]
      }
    },
    useSortBy,
    usePagination
  );
```

We put a select box inside of a react-table cell, and when the user changes the value it updates the props that power the data table. This causes the table to go back to the first page, but I actually want it to stay on the page that the user is currently on. My preferred approach is to control the navigation by using the gotoPage function, but I don't want to manuallyPaginate myself. I would like the component to handle the bulk of the pagination, but I want to override the behavior in a specific scenario.

**Comment by sep2** [comment]
I don't use this library anymore but I believe you could mention the maintainer @[tannerlinsley](https://github.com/tannerlinsley).

**Comment by jphawk** [comment]
I experience the same issue. With React 17 not manual pagination was working on every other click, but after React 18 upgrade `nextPage` and `previousPage` events just don't fire at all. Events fire as expected with `manualPagination` though.

**Comment by austinphan-multiplier** [comment]
@jphawk  I met this issue in React@18. Fix this issue by manually calculate `pageCount`

```
 const tableInstance = useTable({
    pageSize,
    manualPagination,
    pageCount:  Math.ceil((data.length + pageSize - 1) / pageSize). <=== Add this line
})
```

Reason: https://github.com/TanStack/table/blob/06703a56890122cedf1b2fa4b82982999537774e/src/plugin-hooks/usePagination.js#L46
The `pageCount` is `undefined` if we don't set and cause the actions failed
