### ISSUE TITLE
Crash selecting rows in table with grouping and subRows

### ISSUE THREAD

**Issue by fjcalzado** [tannerlinsley/react-table#2465]
**Describe the bug**

When using a table with `useGroupBy`, `useExpanded` and `useRowSelect` plugins, it crashes upon selecting rows when a table is grouped by any column and original data already contains nested `subRows`.

**Provide an example via Codesandbox!**

[https://codesandbox.io/s/react-table-grouping-selection-subrows-66t0y?file=/src/App.js](https://codesandbox.io/s/react-table-grouping-selection-subrows-66t0y?file=/src/App.js)

**Steps To Reproduce**

1. Go to [codesandbox demo](https://codesandbox.io/s/react-table-grouping-selection-subrows-66t0y?file=/src/App.js).
2. Group table by any groupable column (e.g: 'status' column).
3. Select either a grouped row or a row with nested subrows.
4. Crash!

**Expected behavior (Recommended)**

I would expect selection to be done with no failure in the clicked row along with its subrows (recursively).

**Screenshots**

![2020-06-19_11-47-09](https://user-images.githubusercontent.com/24454225/85120266-4c2f7700-b223-11ea-84c7-bb2b218b6c77.gif)

**Desktop (please complete the following information):**

- OS: Windows 10 v10.0.17763
- Browser: Chrome
- Version: 83.0.4103.106

**Additional context**

The culprit seems to be [here](https://github.com/tannerlinsley/react-table/blob/bb248e988f49665acf4ea0d2318df5f304d30efe/src/plugin-hooks/useRowSelect.js#L137). When retrieving nested subRows by `id`, they are not available in `rowsById` structure (they dissapear from there when grouping).

**Comment by tannerlinsley** [comment]
Yeah, looks like a bug. Would you like to submit a PR to fix it?

**Comment by centrodph** [comment]
@tannerlinsley I can take a look

**Comment by tannerlinsley** [comment]
I *think* this is fixed in the latest version. Let me know if it's not.

**Comment by RaiVaibhav** [comment]
@tannerlinsley issue is still there, it's crashing with error `Cannot read property 'isGrouped' of undefined`

**Comment by centrodph** [comment]
@tannerlinsley yes, this one is still there. The selection is fired two times with different information. I have to dig deeper to find the real cause of it.

**Comment by tannerlinsley** [comment]
We’re having some issues releasing the latest version so that may be why. Hang tight

Tanner Linsley

**Comment by gargroh** [comment]
Guessing - can this be because of react strict mode

**Comment by Evadon-Nathan** [comment]
This is the only issue I could find that is related to what I am experiencing. So I apologise if this issue is no longer relevant, but it seems like it is. 

I cannot get react-table to work when the data has subrows and is grouped and needing to use the selection functionality.

I get "Cannot read properties of undefined (reading 'isGrouped')    useRowSelect.js:157"
