### ISSUE TITLE
[docs] 404 Material UI Kitchen Sink

### ISSUE THREAD

**Issue by brian-gates** [tannerlinsley/react-table#2539]
**Describe the bug (required)**
404 in response to https://react-table.tanstack.com/docs/examples/material-ui-kitchen-sink as linked in [the docs](https://react-table.tanstack.com/docs/examples/filtering)

**Comment by SteveSchreiner** [comment]
This would be very useful to see

**Comment by SteveSchreiner** [comment]
found it in the source https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/material-UI-kitchen-sink

**Comment by tannerlinsley** [comment]
Fixed in latest commit :)

**Comment by theGirrafish** [comment]
It seems that some of the codesanbox links are still broken due to the capitalization of the word `ui`.
Example:
- https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/material-ui-components should be https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/material-UI-components
- https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/material-ui-kitchen-sink should be https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/material-UI-kitchen-sink
- https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/bootstrap-ui-components should be https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/bootstrap-UI-components

Either that or the name of the directories need to be changed to lowercase:
- https://github.com/tannerlinsley/react-table/tree/master/examples/material-UI-components
- https://github.com/tannerlinsley/react-table/tree/master/examples/material-UI-kitchen-sink
- https://github.com/tannerlinsley/react-table/tree/master/examples/bootstrap-UI-components

Also the https://react-table.tanstack.com/docs/examples/material-ui-kitchen-sink link is still broken inside the docs
