### ISSUE TITLE
isSelected is undefined in selectedFlatRows when row is filtered

### ISSUE THREAD

**Issue by Buuntu** [tannerlinsley/react-table#2601]
**Bug**
This might be a duplicate of https://github.com/tannerlinsley/react-table/issues/2210, although I don't think it's identical.

When trying to toggle a row manually with filtering, you get weird behavior when a "hidden" row is toggled for selection.  Usually this results in the message:
```
Type Error:

Cannot read property 'isSelected' of undefined
```

Setting the appropriate row in selectedRowIds to false doesn't work either because it doesn't cause a re-render.  As far as I know there isn't an easy workaround to this?

**Codesandbox**
https://codesandbox.io/s/react-table-editable-example-with-filter-my3p7?file=/src/App.js

To replicate:
1) select a row that will be hidden by the global filter
2) click "remove" underneath the table which calls toggleRowSelected()

**Expected behavior**
selectedFlatRows should be the same as selectedRowIds.  I'm not sure how to change the selection state with filtering otherwise, maybe there's a workaround that I'm no aware of but I feel like this is common enough that it should be in the docs at least.

**Comment by tannerlinsley** [comment]
Fixed in latest version 🤞

**Comment by Buuntu** [comment]
> Fixed in latest version 🤞

7.5.2?  I still get the same issue in the Codesandbox example up above.
