### ISSUE TITLE
[Bug] useRowSelect. Parent row in [all selected] state when some subrows are not selected

### ISSUE THREAD

**Issue by xiaoyu-tamu** [tannerlinsley/react-table#2618]
**Describe the bug (required)**

parent row checkbox state is not correct, see screenshot and steps.

**Provide an example via Codesandbox! (required)**
Go to https://codesandbox.io/s/dark-feather-k4jj7?file=/src/App.js

**Steps To Reproduce (required)**

1. Go to https://codesandbox.io/s/dark-feather-k4jj7?file=/src/App.js
2. expand 2nd row
3. select 2nd row 
4. deselect 3th row

**Expected behavior (Recommended)**

2nd row checkbox should in intermediate state, since not all sub rows are selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/33362998/89826667-3439ec80-db1c-11ea-9f59-fd054c387127.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/33362998/89827107-dd80e280-db1c-11ea-8dda-61e2c46cf142.png)

**Additional context**

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version now

**Comment by xiaoyu-tamu** [comment]
I just tried with v7.5.2, looks like the problem still exist.
![image](https://user-images.githubusercontent.com/33362998/95038525-f24ca300-0693-11eb-9f83-1e0be9770c7f.png)

**Comment by SergiiTykhenko** [comment]
Hi @tannerlinsley, bug still exists in v7.6.1
